/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefWorkerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.RefugeeCampEnterprise;
import Business.Organization.Organization;
import Business.Organization.ReliefWorkerOrganization;
import Business.Refugees.Refugee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vignesh
 */
public class RefugeeDetailsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Refugee refugee;
    /**
     * Creates new form RefugeeDetailsJPanel
     */
    public RefugeeDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = (RefugeeCampEnterprise) enterprise;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        uploadPhotoTextField = new javax.swing.JTextField();
        uploadPhotoBtn = new javax.swing.JButton();
        lastNameLbl = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        streetAddressLbl1 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        countryOriginTextField = new javax.swing.JTextField();
        streetAddressLbl2 = new javax.swing.JLabel();
        streetAddressLbl3 = new javax.swing.JLabel();
        streetAddressLbl4 = new javax.swing.JLabel();
        streetAddressLbl5 = new javax.swing.JLabel();
        streetAddressLbl6 = new javax.swing.JLabel();
        maleJRadioButton = new javax.swing.JRadioButton();
        femalejRadioButton = new javax.swing.JRadioButton();
        PhysicallychallengedCheckBox = new javax.swing.JCheckBox();
        medicalAttentionCheckBox = new javax.swing.JCheckBox();
        AccomodationjCheckBox = new javax.swing.JCheckBox();
        addRefugeejButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        uploadPhotoLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        resetjButton1 = new javax.swing.JButton();

        uploadPhotoTextField.setToolTipText("enter filepath");

        uploadPhotoBtn.setText("Browse ");
        uploadPhotoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPhotoBtnActionPerformed(evt);
            }
        });

        lastNameLbl.setText("Name (LastName, FirstName:)");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        streetAddressLbl1.setText("Age:");

        ageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextFieldActionPerformed(evt);
            }
        });

        countryOriginTextField.setToolTipText("");
        countryOriginTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryOriginTextFieldFocusGained(evt);
            }
        });
        countryOriginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryOriginTextFieldActionPerformed(evt);
            }
        });

        streetAddressLbl2.setText("Country of Origin:");

        streetAddressLbl3.setText("Sex:");

        streetAddressLbl4.setText("Require Accomodation:");

        streetAddressLbl5.setText("Physically Challenged: ");

        streetAddressLbl6.setText("Require Medical Attention:");

        buttonGroup1.add(maleJRadioButton);
        maleJRadioButton.setText("Male");
        maleJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleJRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(femalejRadioButton);
        femalejRadioButton.setText("Female");

        addRefugeejButton.setText("Add Refugee");
        addRefugeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRefugeejButtonActionPerformed(evt);
            }
        });

        resetjButton.setText("Reset");
        resetjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButtonActionPerformed(evt);
            }
        });

        uploadPhotoLbl.setText("Upload Photo:");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Refugee Details");

        resetjButton1.setText("Back");
        resetjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resetjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(addRefugeejButton)
                                        .addGap(353, 353, 353)
                                        .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(streetAddressLbl2)
                                                .addComponent(streetAddressLbl5)
                                                .addComponent(streetAddressLbl6)
                                                .addComponent(streetAddressLbl4)
                                                .addComponent(streetAddressLbl3)
                                                .addComponent(streetAddressLbl1))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(AccomodationjCheckBox)
                                                .addComponent(medicalAttentionCheckBox)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(maleJRadioButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(femalejRadioButton))
                                                .addComponent(PhysicallychallengedCheckBox)
                                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(countryOriginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(uploadPhotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lastNameLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uploadPhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uploadPhotoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(373, 373, 373))))
                .addGap(0, 168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PhysicallychallengedCheckBox)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(streetAddressLbl1)
                                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(countryOriginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(streetAddressLbl2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(maleJRadioButton)
                                            .addComponent(femalejRadioButton))
                                        .addGap(30, 30, 30)))
                                .addGap(30, 30, 30))
                            .addComponent(medicalAttentionCheckBox))
                        .addGap(30, 30, 30))
                    .addComponent(AccomodationjCheckBox)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(streetAddressLbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(streetAddressLbl5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(streetAddressLbl6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(streetAddressLbl4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uploadPhotoBtn)
                        .addComponent(uploadPhotoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uploadPhotoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRefugeejButton)
                    .addComponent(resetjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(resetjButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadPhotoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPhotoBtnActionPerformed
        //JFileChooser class enables us to choose a file from a pop-up window. In our case, choose a photo
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        uploadPhotoTextField.setText(filename);
        refugee.setPicture(filename);

    }//GEN-LAST:event_uploadPhotoBtnActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void ageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextFieldActionPerformed

    private void countryOriginTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryOriginTextFieldFocusGained
        countryOriginTextField.setText("");
    }//GEN-LAST:event_countryOriginTextFieldFocusGained

    private void countryOriginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryOriginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryOriginTextFieldActionPerformed

    private void maleJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleJRadioButtonActionPerformed

    private void addRefugeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRefugeejButtonActionPerformed
        // TODO add your handling code here:
        Refugee refugee = new Refugee();
        if (nameTextField != null && !nameTextField.getText().trim().isEmpty()) {
            refugee.setName(nameTextField.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Enter refugee name", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (ageTextField != null && !ageTextField.getText().trim().isEmpty()) {
            Integer age = Integer.parseInt(ageTextField.getText());
            if (age >= 0 && age <= 120) {
                refugee.setAge(age);
            } else {
                JOptionPane.showMessageDialog(null, "Enter correct Age[0-120]", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter valid age", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (countryOriginTextField != null && !countryOriginTextField.getText().trim().isEmpty()) {
            refugee.setOriginCountry(countryOriginTextField.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Enter Country of Origin", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (maleJRadioButton.isSelected() || femalejRadioButton.isSelected()) {
            refugee.setSex(maleJRadioButton.isSelected());
        } else {
            JOptionPane.showMessageDialog(null, "Select Sex", "Error", JOptionPane.ERROR_MESSAGE);
        }

        refugee.setPhysicallyChallenged(PhysicallychallengedCheckBox.isSelected());
        refugee.setNeedsMedicalAttn(medicalAttentionCheckBox.isSelected());
        refugee.setHasAccomodation(AccomodationjCheckBox.isSelected());
        this.enterprise.getRefugeeDirectory().createRefugee(refugee);
        /*ImageIcon icon = new ImageIcon(refugee.getPicture());
        photoLbl.setIcon(icon);*/

        JOptionPane.showConfirmDialog(null, "New Refugee is added");
        nameTextField.setText("");
        ageTextField.setText("");
        countryOriginTextField.setText("");
        buttonGroup1.clearSelection();
        PhysicallychallengedCheckBox.setSelected(false);
        AccomodationjCheckBox.setSelected(false);
        medicalAttentionCheckBox.setSelected(false);
    }//GEN-LAST:event_addRefugeejButtonActionPerformed

    private void resetjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButtonActionPerformed
        // TODO add your handling code here:
        nameTextField.setText("");
        ageTextField.setText("");
        countryOriginTextField.setText("");
        buttonGroup1.clearSelection();
        PhysicallychallengedCheckBox.setSelected(false);
        AccomodationjCheckBox.setSelected(false);
        medicalAttentionCheckBox.setSelected(false);
    }//GEN-LAST:event_resetjButtonActionPerformed

    private void resetjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ReliefWorkerWorkAreaJPanel", new ReliefWorkerWorkAreaJPanel(userProcessContainer, userAccount, (ReliefWorkerOrganization) organization, enterprise));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_resetjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AccomodationjCheckBox;
    private javax.swing.JCheckBox PhysicallychallengedCheckBox;
    private javax.swing.JButton addRefugeejButton;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField countryOriginTextField;
    private javax.swing.JRadioButton femalejRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JRadioButton maleJRadioButton;
    private javax.swing.JCheckBox medicalAttentionCheckBox;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton resetjButton;
    private javax.swing.JButton resetjButton1;
    private javax.swing.JLabel streetAddressLbl1;
    private javax.swing.JLabel streetAddressLbl2;
    private javax.swing.JLabel streetAddressLbl3;
    private javax.swing.JLabel streetAddressLbl4;
    private javax.swing.JLabel streetAddressLbl5;
    private javax.swing.JLabel streetAddressLbl6;
    private javax.swing.JButton uploadPhotoBtn;
    private javax.swing.JLabel uploadPhotoLbl;
    private javax.swing.JTextField uploadPhotoTextField;
    // End of variables declaration//GEN-END:variables
}
