/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefWorkerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.InventoryManagerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicalSupplyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestMedicalJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form RequestSupplyJPanel
     */
    public RequestMedicalJPanel(JPanel userProcessContainer, UserAccount UserAccount, Organization organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = UserAccount;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        countJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refugeeIDJTextField = new javax.swing.JTextField();
        searchRefugee = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setText("Create Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel1.setText("Count:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));
        add(countJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));

        jLabel2.setText("Refugee IDs:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, -1));

        refugeeIDJTextField.setEnabled(false);
        add(refugeeIDJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, -1));

        searchRefugee.setText("Search");
        searchRefugee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRefugeeActionPerformed(evt);
            }
        });
        add(searchRefugee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 110, -1));

        jLabel3.setText("Description:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 90, -1));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String requiredMedikits = countJTextField.getText();
        int count = 0;
        if (!requiredMedikits.trim().isEmpty()) {
            count = Integer.parseInt(requiredMedikits) <= 0 ? 0 : Integer.parseInt(requiredMedikits);
        }

        String message = messageJTextField.getText();
        WorkRequest request = null;
        Organization org = null;

        request = new MedicalSupplyWorkRequest();
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof InventoryManagerOrganization) {
                org = organization;
                break;
            }
        }
        request.setMessage(message);
        request.setSender(userAccount);
        request.setCount(count);
        request.setStatus("Sent");
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestSupplyJPanel", new RequestSupplyJPanel(userProcessContainer, userAccount, organization, enterprise));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void searchRefugeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRefugeeActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("SearchRefugeeJPanel", new SearchRefugeeJPanel(userProcessContainer, userAccount, organization, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_searchRefugeeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField countJTextField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField refugeeIDJTextField;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton searchRefugee;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
