/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ReliefWorkerRole;

import userinterface.DoctorRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.MedicalOrganization;
import Business.Organization.Organization;
import Business.Organization.ReliefWorkerOrganization;
import Business.Organization.ShelterOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodSupplyWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.MedicalSupplyWorkRequest;
import Business.WorkQueue.ShelterAllocationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestSupplyJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private UserAccount userAccount;

    /**
     * Creates new form RequestSupplyJPanel
     */
    public RequestSupplyJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        foodRBtn = new javax.swing.JRadioButton();
        ShelterRBtn = new javax.swing.JRadioButton();
        medicalRBtn = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(248, 249, 249));
        requestTestJButton.setText("Create Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        backJButton.setBackground(new java.awt.Color(248, 249, 249));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 30));

        buttonGroup1.add(foodRBtn);
        foodRBtn.setText("Food Request");
        foodRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodRBtnActionPerformed(evt);
            }
        });
        add(foodRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        buttonGroup1.add(ShelterRBtn);
        ShelterRBtn.setText("Shelter Request");
        ShelterRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShelterRBtnActionPerformed(evt);
            }
        });
        add(ShelterRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        buttonGroup1.add(medicalRBtn);
        medicalRBtn.setText("Medical Request");
        add(medicalRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        // String message = messageJTextField.getText();
        WorkRequest request = null;
        Organization org = null;

        if (foodRBtn.isSelected()) {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestFoodJPanel", new RequestFoodJPanel(userProcessContainer, userAccount, organization, enterprise, null));
            layout.next(userProcessContainer);

        } else if (ShelterRBtn.isSelected()) {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestShelterJPanel", new RequestShelterJPanel(userProcessContainer, userAccount, organization, enterprise, null));
            layout.next(userProcessContainer);
        } else if (medicalRBtn.isSelected()) {
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            userProcessContainer.add("RequestMedicalJPanel", new RequestMedicalJPanel(userProcessContainer, userAccount, organization, enterprise, null));
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Request radio button", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("ReliefWorkerWorkAreaJPanel", new ReliefWorkerWorkAreaJPanel(userProcessContainer, userAccount, (ReliefWorkerOrganization) organization, enterprise));
        layout.next(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void foodRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodRBtnActionPerformed

    private void ShelterRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShelterRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShelterRBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ShelterRBtn;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JRadioButton foodRBtn;
    private javax.swing.JRadioButton medicalRBtn;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
